### ISSUE TITLE
Getting [object Object] error.

### ISSUE THREAD

**Issue by basil2style** [javebratt/ionic2-firebase3-facebook-auth#1]
When I try to do the Firebase facebook login, I am getting a facebook dialog without receiving any error message.
Please check this page : https://forum.ionicframework.com/t/error-after-firebase-authentication-using-facebook/99849

**Comment by javebratt** [comment]
If you go through `Chrome > Tools > Inspect Devices` you can see the console and let me know what error it's showing.

**Comment by basil2style** [comment]
It's just throwing {} from _this.facebook.login(['email']).then((response)_ catch function

**Comment by javebratt** [comment]
I see you closed the issue, did you figure out what was wrong?

**Comment by basil2style** [comment]
Yeah, it was my mistake :)
